kind: Deployment
apiVersion: apps/v1
metadata:
  name: actions-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions-demo
  template:
    metadata:
      labels:
        app: actions-demo
    spec:
      containers:
        - name: actions-demo-application
          image: actions-demo:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: actions-demo-svc
spec:
  ports:
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: actions-demo-app